PI_CMD_TRANSIT_WAYPOINTS = 0x01
PI_CMD_ROTATE_AND_DRIVE  = 0x02
PI_CMD_SET_BOT_OPTION    = 0x03
PI_CMD_FIND_OBJECT       = 0x04
PI_CMD_CALIBRATE_CAMERA  = 0x05
PI_CMD_REPORT_STATUS     = 0x06

PI_OPTION_FOLLOW_ME_MODE        = 0x01
PI_OPTION_UPLOAD_SNAPSHOTS      = 0x02

BOT_OPTION_CALIBRATE            = 0xB0
BOT_OPTION_RESET_TO_ORIGIN      = 0xB1
BOT_OPTION_SET_PID_PARAMETERS   = 0xB2

BOT_OPTION2_ROTATE              = 0xB3
BOT_OPTION2_REPORTSTATUS        = 0xB4